/**
 * Program assembly (rev 2, flat model): the planner (or template) authors only
 * the program body; assembly prepends the header holding verbatim lane prompt
 * text (PROMPTS), per-bot adjudication guidance (NOTES), structured-output
 * schemas (SCHEMAS), deterministic run facts (CTX), the aggregator's canonical
 * instructions (MERGE_PROMPT), and the aggregator lane options (AGG). Judgment
 * text is verbatim by construction — the planner never holds prompt bodies.
 */
import {
  flatLanes,
  type AggregatorOptions,
  type CompiledReviewer,
  type Facts,
} from "./contracts.js";
import { CONSOLIDATED_SCHEMA, FINDINGS_SCHEMA } from "./schemas.js";

export interface AssemblyInput {
  reviewers: CompiledReviewer[]; // eligible cohort, declaration order
  facts: Facts;
  headSha: string;
  matchedRules: string[];
  aggregator: AggregatorOptions;
}

export function promptTable(reviewers: CompiledReviewer[]): Record<string, string> {
  const table: Record<string, string> = {};
  for (const lane of flatLanes(reviewers)) table[lane.promptKey] = lane.promptText;
  return table;
}

export const MERGE_PROMPT = `You are the aggregator — the single consolidation stage of an automated code review, and the only place findings merge. You receive every lane's settled findings envelope (lanes are labeled by key; a key's prefix is the reviewer bot that owns it; a merged lane carries several keys). Produce ONE consolidated result, deduplicating aggressively — beyond what any single lane asked for:
- Same defect, any wording: findings describing one underlying defect merge into one, regardless of lane, severity, or exact line. A merged finding inherits the WORST source severity and its "reviewers" array is the union of sourcing bot ids.
- Symptom chains collapse: when one finding is the cause and others its downstream symptoms, keep the cause and fold the symptoms into its rationale.
- Pattern repetition compresses: the same defect at N sites becomes ONE finding enumerating the sites.
- Adjacent nits coalesce: low-severity observations about the same hunk merge into a single entry.
- Severity discipline: disagreement may downgrade a finding exactly one rank, never below nit. Never drop a blocking finding except by merging it into another blocking finding. Never invent findings no lane reported.
- Attribution: "reviewers" arrays may only contain the bot ids you were given. Honor each bot's aggregation notes (NOTES) when judging findings sourced only from that bot's lanes; weigh them when merging across bots.
- Failure honesty: every errored lane becomes an omission. If EVERY lane errored, set readiness to "unknown". Otherwise judge from the lanes that succeeded.
- readiness: "ready" only if the change is safe to land as-is given the surviving findings; else "not_ready" (or "unknown" per the rule above).
- summary: two sentences max, plain prose.`;

export function assemble(input: AssemblyInput, body: string): string {
  const prompts = promptTable(input.reviewers);
  const notes: Record<string, string> = {};
  for (const r of input.reviewers) {
    if (r.aggregationNotes) notes[r.id] = r.aggregationNotes;
  }
  const ctx = {
    repository: input.facts.repository,
    baseRef: input.facts.baseRef,
    headSha: input.headSha,
    changedPaths: input.facts.changedPaths.slice(0, 400),
    matchedRules: input.matchedRules,
    reviewers: input.reviewers.map((r) => ({
      id: r.id,
      displayName: r.displayName,
      canBlock: r.canBlock,
      required: r.required,
      laneKeys: r.lanes.map((l) => l.promptKey),
    })),
  };
  const header = `// GENERATED by orc-review — header is injected; do not hand-edit.
const PROMPTS = ${JSON.stringify(prompts, null, 2)} as const;
const NOTES = ${JSON.stringify(notes, null, 2)} as const;
const SCHEMAS = { findings: ${JSON.stringify(FINDINGS_SCHEMA)}, consolidated: ${JSON.stringify(CONSOLIDATED_SCHEMA)} } as const;
const CTX = ${JSON.stringify(ctx, null, 2)} as const;
const MERGE_PROMPT = ${JSON.stringify(MERGE_PROMPT)};
const AGG = ${JSON.stringify(input.aggregator)} as const;
void PROMPTS; void NOTES; void SCHEMAS; void CTX; void MERGE_PROMPT; void AGG;
`;
  return `${header}\n${body.trim()}\n`;
}
